[project]
name = "oracle.oci-fleet-application-management-mcp-server"
version = "0.0.0"
description = "OCI Fleet Application Management MCP server"
readme = "README.md"
requires-python = ">=3.13"
license = "UPL-1.0"
license-files = ["LICENSE.txt"]
