[project]
name = "oracle.oci-email-delivery-mcp-server"
version = "0.0.0"
description = "OCI Email Delivery MCP server"
readme = "README.md"
requires-python = ">=3.13"
license = "UPL-1.0"
license-files = ["LICENSE.txt"]
